const allData = [
  {
    id: 1,
    image:
      "https://5.imimg.com/data5/SELLER/Default/2021/2/LG/QZ/AV/947710/royal-blue-500x500-1000x1000.jpeg",
    title: "Victorian Fashion",
    text: "Outerwear Fashion Design ",
    price: 152,
    fav: false,
    number: 0,
    categorie: "BestSeller",
  },
  {
    id: 2,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRM0a3GTiNpjsI7u4zhbO2VW03pEhtWnz1l5UzDAddYit1MrPFzy5YfS28VQfqlgRJM3tI&usqp=CAU",
    title: "Gregorian Fashion",
    text: "Outerwear Fashion Design",
    price: 123,
    fav: false,
    number: 0,
    categorie: "BestSeller",
  },
  {
    id: 3,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSME14dxpiCEXFSNNW6tg4WOwLxDJiB-eIWwEV8saU5ilTUCcGAhF-Wwg5YM_gT1g9ombM&usqp=CAU",
    title: "Victorian Fashion",
    text: "Outerwear Fashion Design",
    price: 111,
    fav: false,
    number: 0,
    categorie: "BestSeller",
  },
  {
    id: 4,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSeZ3mKiejTHX25Rpo_5xBWeKpin500jnYnfj_1ohvhezaak1qMNdjtmwgxtpExH0XWPhQ&usqp=CAU",
    title: "Gregorian Fashion",
    text: "Outerwear Fashion Design",
    price: 342,
    fav: false,
    number: 0,
    categorie: "BestSeller",
  },
  {
    id: 5,
    image:
      "https://productcatalogue2015.s3.amazonaws.com/ALT-BBM-GY_460_350.jpg",
    title: "Victorian Fashion",
    text: "Outerwear Fashion Design",
    price: 222,
    fav: false,
    number: 0,
    categorie: "BestSeller",
  },
  {
    id: 6,
    image:
      "https://productcatalogue2020.s3.amazonaws.com/ALT-BBM-CY_460_350.jpg",
    title: "Gregorian Fashion",
    text: "Outerwear Fashion Design",
    price: 144,
    fav: false,
    number: 0,
    categorie: "BestSeller",
  },
  {
    id: 7,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTf0OBGCfB0yox8fQ9u-UrmKj6rAMGzExH2KhMY2kTAy1P2-ry_gjaNHTZr4oUZOQuR14&usqp=CAU",
    title: "Victorian Fashion",
    text: "Outerwear Fashion Design",
    price: 122,
    fav: false,
    number: 0,
    categorie: "BestSeller",
  },
  {
    id: 8,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQdUA_1S6dGd081Mdbk2etbDOvJHZH9t3ElAlVrHFBJPzn8QUHwOkNPEP2ilYqpkySbtA&usqp=CAU",
    title: "Gregorian Fashion",
    text: "Outerwear Fashion Design",
    price: 321,
    fav: false,
    number: 0,
    categorie: "BestSeller",
  },

  {
    id: 9,
    image: "https://m.media-amazon.com/images/I/91NPUHqu0aL._AC_UX569_.jpg",
    title: "Victorian Fashion",
    text: "Outerwear Fashion Design",
    price: 321,
    new: "Sales -5 %",
    fav: false,
    number: 0,
    color: "productCard-flex-sale",
    categorie: "Outlet",
  },
  {
    id: 10,
    image: "https://m.media-amazon.com/images/I/5148512rs0L._AC_SX522_.jpg",
    title: "Gregorian Fashion",
    text: "Outerwear Fashion Design",
    price: 453,
    new: "Sales -3 %",
    fav: false,
    number: 0,
    color: "productCard-flex-sale",
    categorie: "Outlet",
  },
  {
    id: 11,
    image:
      "https://img.sport24.dk/catalog/product/cache/7f192f0def86e0dc4c6d9f4d22381931/3/b/3b-cj2301_010_01.jpg",
    title: "Victorian Fashion",
    text: "Outerwear Fashion Design",
    price: 321,
    new: "Sales -12 %",
    fav: false,
    number: 0,
    color: "productCard-flex-sale",
    categorie: "Outlet",
  },
  {
    id: 12,
    image:
      "https://dunkshop.ro/media/catalog/product/cache/2ab5632e2cd36be345ff0e4a3554de39/z/a/zach-lavine-chicago-bulls-nba-t-shirt-dr6367-104-front.jpg",
    title: "Gregorian Fashion",
    text: "Outerwear Fashion Design",
    price: 676,
    new: "Sales -12 %",
    fav: false,
    number: 0,
    color: "productCard-flex-sale",
    categorie: "Outlet",
  },
  {
    id: 13,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1hEbQLCVi6Con1Y69JgdqVSYDlkLeSlqBsjNvIpVAlmJrTgoG85f8l92zVe3Ns81pp8U&usqp=CAU",
    title: "Victorian Fashion",
    text: "Outerwear Fashion Design",
    price: 75,
    new: "Sales -1 %",
    fav: false,
    number: 0,
    color: "productCard-flex-sale",
    categorie: "Outlet",
  },
  {
    id: 14,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMeGYgeOBnmLU8YPXIu-Ab6vPSp_g1bvdCLD59Dfhhiwj4J6mCzHKhyJQ_jN-5KE_ZQyI&usqp=CAU",
    title: "Gregorian Fashion",
    text: "Outerwear Fashion Design",
    price: 154,
    new: "Sales -2 %",
    fav: false,
    number: 0,
    color: "productCard-flex-sale",
    categorie: "Outlet",
  },
  {
    id: 15,
    image:
      "https://se.basketzone.net/zdjecia/2020/12/29/112/57/NIKE_NBA_CHICAGO_BULLS_CITY_EDITION_LOGO_DRI_FIT_TEE_BLACK-mini.jpg",
    title: "Victorian Fashion",
    text: "Outerwear Fashion Design",
    price: 132,
    new: "Sales -25 %",
    fav: false,
    number: 0,
    color: "productCard-flex-sale",
    categorie: "Outlet",
  },
  {
    id: 16,
    image:
      "https://cdn-images.farfetch-contents.com/16/77/61/92/16776192_33773020_480.jpg",
    title: "Gregorian Fashion",
    text: "Outerwear Fashion Design",
    price: 157,
    new: "Sales -22 %",
    fav: false,
    number: 0,
    color: "productCard-flex-sale",
    categorie: "Outlet",
  },
  {
    id: 17,
    image:
      "https://cdn.shopify.com/s/files/1/0603/7533/5145/products/7front2-small_ec509190-772d-437f-b5d7-ad2a69ee42a6.jpg?v=1649851198",
    title: "Victorian Fashion",
    text: "Outerwear Fashion Design",
    price: 157,
    fav: false,
    number: 0,
    new: "New",
    color: "productCard-flex-new",
    categorie: "NewArrivals",
  },
  {
    id: 18,
    image:
      "https://www.tradeinn.com/f/13936/139366871_2/scotch---soda-dip-dye-jersey-short-sleeve-t-shirt.jpg",
    title: "Gregorian Fashion",
    text: "Outerwear Fashion Design",
    price: 154,
    fav: false,
    number: 0,
    new: "New",
    color: "productCard-flex-new",
    categorie: "NewArrivals",
  },
  {
    id: 19,
    image:
      "https://i.etsystatic.com/34467542/r/il/15ea29/4531051410/il_fullxfull.4531051410_qdf6.jpg",
    title: "Victorian Fashion",
    text: "Outerwear Fashion Design",
    price: 140,
    fav: false,
    number: 0,
    new: "New",
    color: "productCard-flex-new",
    categorie: "NewArrivals",
  },
  {
    id: 20,
    image:
      "https://www.topsportcraiova.ro/files/images/products/Adidas-Tee-HF7476-1_full.jpg",
    title: "Gregorian Fashion",
    text: "Outerwear Fashion Design",
    price: 110,
    fav: false,
    number: 0,
    new: "New",
    color: "productCard-flex-new",
    categorie: "NewArrivals",
  },
  {
    id: 21,
    image:
      "https://www.topsportcraiova.ro/files/images/products/Adidas-Tee-HF7474-1_full.jpg",
    title: "Victorian Fashion",
    text: "Outerwear Fashion Design",
    price: 140,
    fav: false,
    number: 0,
    new: "New",
    color: "productCard-flex-new",
    categorie: "NewArrivals",
  },
  {
    id: 22,
    image:
      "https://www.topsportcraiova.ro/files/images/products/Adidas-Tee-HF7474-1_full.jpg",
    title: "Gregorian Fashion",
    text: "Outerwear Fashion Design",
    price: 150,
    fav: false,
    number: 0,
    new: "New",
    color: "productCard-flex-new",
    categorie: "NewArrivals",
  },
  {
    id: 23,
    image: "https://thumblr.uniid.it/product/255156/9e2372b622e0.jpg",
    title: "Victorian Fashion",
    text: "Outerwear Fashion Design",
    price: 150,
    fav: false,
    number: 0,
    new: "New",
    color: "productCard-flex-new",
    categorie: "NewArrivals",
  },
  {
    id: 24,
    image:
      "https://www.topsportcraiova.ro/files/images/products/Adidas-Tee-HF7475-1_full.jpg",
    title: "Gregorian Fashion",
    text: "Outerwear Fashion Design",
    price: 120,
    fav: false,
    number: 0,
    new: "New",
    color: "productCard-flex-new",
    categorie: "NewArrivals",
  },
];

export default allData;
