const NewArrivas = [
  {
    id: 17,
    image:
      "https://cdn.shopify.com/s/files/1/0603/7533/5145/products/7front2-small_ec509190-772d-437f-b5d7-ad2a69ee42a6.jpg?v=1649851198",
    title: "Victorian Fashion",
    text: "Outerwear Fashion Design",
    price: 157,
    fav: false,
    number: 0,
    new: "New",
    color: "productCard-flex-new",
    categorie: "NewArrivals",
  },
  {
    id: 18,
    image:
      "https://www.tradeinn.com/f/13936/139366871_2/scotch---soda-dip-dye-jersey-short-sleeve-t-shirt.jpg",
    title: "Gregorian Fashion",
    text: "Outerwear Fashion Design",
    price: 154,
    fav: false,
    number: 0,
    new: "New",
    color: "productCard-flex-new",
    categorie: "NewArrivals",
  },
  {
    id: 19,
    image:
      "https://i.etsystatic.com/34467542/r/il/15ea29/4531051410/il_fullxfull.4531051410_qdf6.jpg",
    title: "Victorian Fashion",
    text: "Outerwear Fashion Design",
    price: 140,
    fav: false,
    number: 0,
    new: "New",
    color: "productCard-flex-new",
    categorie: "NewArrivals",
  },
  {
    id: 20,
    image:
      "https://www.topsportcraiova.ro/files/images/products/Adidas-Tee-HF7476-1_full.jpg",
    title: "Gregorian Fashion",
    text: "Outerwear Fashion Design",
    price: 110,
    fav: false,
    number: 0,
    new: "New",
    color: "productCard-flex-new",
    categorie: "NewArrivals",
  },
  {
    id: 21,
    image:
      "https://www.topsportcraiova.ro/files/images/products/Adidas-Tee-HF7474-1_full.jpg",
    title: "Victorian Fashion",
    text: "Outerwear Fashion Design",
    price: 140,
    fav: false,
    number: 0,
    new: "New",
    color: "productCard-flex-new",
    categorie: "NewArrivals",
  },
  {
    id: 22,
    image:
      "https://www.topsportcraiova.ro/files/images/products/Adidas-Tee-HF7474-1_full.jpg",
    title: "Gregorian Fashion",
    text: "Outerwear Fashion Design",
    price: 150,
    fav: false,
    number: 0,
    new: "New",
    color: "productCard-flex-new",
    categorie: "NewArrivals",
  },
  {
    id: 23,
    image: "https://thumblr.uniid.it/product/255156/9e2372b622e0.jpg",
    title: "Victorian Fashion",
    text: "Outerwear Fashion Design",
    price: 150,
    fav: false,
    number: 0,
    new: "New",
    color: "productCard-flex-new",
    categorie: "NewArrivals",
  },
  {
    id: 24,
    image:
      "https://www.topsportcraiova.ro/files/images/products/Adidas-Tee-HF7475-1_full.jpg",
    title: "Gregorian Fashion",
    text: "Outerwear Fashion Design",
    price: 120,
    fav: false,
    number: 0,
    new: "New",
    color: "productCard-flex-new",
    categorie: "NewArrivals",
  },
];
export default NewArrivas;
