const OutletData = [
  {
    id: 9,
    image: "https://m.media-amazon.com/images/I/91NPUHqu0aL._AC_UX569_.jpg",
    title: "Victorian Fashion",
    text: "Outerwear Fashion Design",
    price: 321,
    new: "Sales -5 %",
    fav: false,
    number: 0,
    color: "productCard-flex-sale",
    categorie: "Outlet",
  },
  {
    id: 10,
    image: "https://m.media-amazon.com/images/I/5148512rs0L._AC_SX522_.jpg",
    title: "Gregorian Fashion",
    text: "Outerwear Fashion Design",
    price: 453,
    new: "Sales -3 %",
    fav: false,
    number: 0,
    color: "productCard-flex-sale",
    categorie: "Outlet",
  },
  {
    id: 11,
    image:
      "https://img.sport24.dk/catalog/product/cache/7f192f0def86e0dc4c6d9f4d22381931/3/b/3b-cj2301_010_01.jpg",
    title: "Victorian Fashion",
    text: "Outerwear Fashion Design",
    price: 321,
    new: "Sales -12 %",
    fav: false,
    number: 0,
    color: "productCard-flex-sale",
    categorie: "Outlet",
  },
  {
    id: 12,
    image:
      "https://dunkshop.ro/media/catalog/product/cache/2ab5632e2cd36be345ff0e4a3554de39/z/a/zach-lavine-chicago-bulls-nba-t-shirt-dr6367-104-front.jpg",
    title: "Gregorian Fashion",
    text: "Outerwear Fashion Design",
    price: 676,
    new: "Sales -12 %",
    fav: false,
    number: 0,
    color: "productCard-flex-sale",
    categorie: "Outlet",
  },
  {
    id: 13,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1hEbQLCVi6Con1Y69JgdqVSYDlkLeSlqBsjNvIpVAlmJrTgoG85f8l92zVe3Ns81pp8U&usqp=CAU",
    title: "Victorian Fashion",
    text: "Outerwear Fashion Design",
    price: 75,
    new: "Sales -1 %",
    fav: false,
    number: 0,
    color: "productCard-flex-sale",
    categorie: "Outlet",
  },
  {
    id: 14,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMeGYgeOBnmLU8YPXIu-Ab6vPSp_g1bvdCLD59Dfhhiwj4J6mCzHKhyJQ_jN-5KE_ZQyI&usqp=CAU",
    title: "Gregorian Fashion",
    text: "Outerwear Fashion Design",
    price: 154,
    new: "Sales -2 %",
    fav: false,
    number: 0,
    color: "productCard-flex-sale",
    categorie: "Outlet",
  },
  {
    id: 15,
    image:
      "https://se.basketzone.net/zdjecia/2020/12/29/112/57/NIKE_NBA_CHICAGO_BULLS_CITY_EDITION_LOGO_DRI_FIT_TEE_BLACK-mini.jpg",
    title: "Victorian Fashion",
    text: "Outerwear Fashion Design",
    price: 132,
    new: "Sales -25 %",
    fav: false,
    number: 0,
    color: "productCard-flex-sale",
    categorie: "Outlet",
  },
  {
    id: 16,
    image:
      "https://cdn-images.farfetch-contents.com/16/77/61/92/16776192_33773020_480.jpg",
    title: "Gregorian Fashion",
    text: "Outerwear Fashion Design",
    price: 157,
    new: "Sales -22 %",
    fav: false,
    number: 0,
    color: "productCard-flex-sale",
    categorie: "Outlet",
  },
];
export default OutletData;
